### ISSUE TITLE
Classes that should be initialized at run time got initialized during image building:

### ISSUE THREAD

**Issue by opjk** [ayltai/spring-graalvm-native-plugin#36]
**Desktop (please complete the following information):**

 - OS:  deepin
 - Version ： v20

**Additional context**

Error: Classes that should be initialized at run time got initialized during image building:
Classes that should be initialized at run time got initialized during image building:

 org.springframework.boot.logging.java.JavaLoggingSystem$Factory was unintentionally initialized at build time. To see why org.springframework.boot.logging.java.JavaLoggingSystem$Factory got initialized use --trace-class-initialization=org.springframework.boot.logging.java.JavaLoggingSystem$Factory
org.springframework.boot.logging.logback.LogbackLoggingSystem$Factory was unintentionally initialized at build time. To see why org.springframework.boot.logging.logback.LogbackLoggingSystem$Factory got initialized use --trace-class-initialization=org.springframework.boot.logging.logback.LogbackLoggingSystem$Factory

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 org.springframework.boot.logging.java.JavaLoggingSystem$Factory was unintentionally initialized at build time. To see why org.springframework.boot.logging.java.JavaLoggingSystem$Factory got initialized use --trace-class-initialization=org.springframework.boot.logging.java.JavaLoggingSystem$Factory
org.springframework.boot.logging.logback.LogbackLoggingSystem$Factory was unintentionally initialized at build time. To see why org.springframework.boot.logging.logback.LogbackLoggingSystem$Factory got initialized use --trace-class-initialization=org.springframework.boot.logging.logback.LogbackLoggingSystem$Factory

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:539)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:226)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:735)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:735)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:558)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1
Image build request failed with exit status 1

**Comment by ayltai** [comment]
It says `Classes that should be initialized at run time got initialized during image building`, so did you include classes to be initialized using `initializeAtBuildTime` as mentioned in the readme? Also, please check how to use GraalVM native: https://www.graalvm.org/reference-manual/native-image/Options/

This plugin is a wrapper to build GraalVM native image so you still need to read their documentation on how it works.

**Comment by opjk** [comment]
Thanks ！！
