### ISSUE TITLE
UnsatisfiedLinkError: no awt in java.library.path

### ISSUE THREAD

**Issue by opjk** [ayltai/spring-graalvm-native-plugin#37]
It is a  desktop Application with  openJFX 15.  Is not support for openJFX ?

./confbox-gui 
Exception in thread "main" java.lang.UnsatisfiedLinkError: no awt in java.library.path
	at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary(NativeLibrarySupport.java:131)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:270)
	at java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.lang.Runtime.loadLibrary(Runtime.java:232)
	at java.lang.System.loadLibrary(System.java:351)
	at java.awt.Toolkit$3.run(Toolkit.java:1395)
	at java.awt.Toolkit$3.run(Toolkit.java:1393)
	at java.security.AccessController.doPrivileged(AccessController.java:84)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1392)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1425)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
	at java.awt.SystemTray.isSupported(SystemTray.java:221)
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.launch(AbstractJavaFxApplicationSupport.java:279)
	at com.gridnt.confbox.gui.ConfBoxApplication.main(ConfBoxApplication.java:24)

**Desktop (please complete the following information):**

 - OS:  deepin 
 - Version  v20

**Additional context**
 gradle configuration:

apply plugin: "org.openjfx.javafxplugin"
apply plugin: 'com.github.ayltai.spring-graalvm-native-plugin'

javafx {
    version = "15"
    modules = ["javafx.base", "javafx.controls", "javafx.fxml", "javafx.graphics", "javafx.media", "javafx.swing", "javafx.web" ]
}

nativeImage {
    mainClassName = 'com.ConfBoxApplication'
    javaVersion = "11"
    reportExceptionStackTraces = true
    removeUnusedAutoConfig = true
    removeYamlSupport = true
    maxHeapSize = '8G'
    initializeAtBuildTime = ['org.apache.commons.logging.LogFactory']
}

**Comment by ayltai** [comment]
This Gradle plugin is a wrapper to execute GraalVM native image commands. For questions related to GraalVM, please go to https://github.com/oracle/graal
