### ISSUE TITLE
Having issue on macOS Catalina 10.15.6

### ISSUE THREAD

**Issue by letrungtrung** [ayltai/spring-graalvm-native-plugin#5]
I got issue when running on MacBook Air, macOS Catalina version 10.15.6
  - Gradle Plugin version:  com.github.ayltai.spring-graalvm-native-plugin' version '1.0.7'
  - Graalvm: java8-20.1.0

Error: Unable to detect supported DARWIN native software development toolchain.
com.oracle.svm.core.util.UserError$UserException: Unable to detect supported DARWIN native software development toolchain.
at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.(CCompilerInvoker.java:72)
at com.oracle.svm.hosted.c.codegen.CCompilerInvoker$DarwinCCompilerInvoker.(CCompilerInvoker.java:205)
at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.create(CCompilerInvoker.java:82)
at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:851)
at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:536)
at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:451)
at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)

**Comment by ayltai** [comment]
From the error stack trace, it is not related to this project.

PS. Don't cross-post asking for help. Mulitple developers might work on it and causing duplicate effort and their time would be wasted. Please be considerate.
https://github.com/oracle/graal/issues/2480#issuecomment-663409619
